Fix Typescript errors
Fixes Typescript errors related to missing properties and incorrect type assignments.
*   Fixes error TS2339: Property 'error' does not exist on type
*   Fixes error TS2322: Type is not assignable to type
*   Fixes error TS2339: Property 'success' does not exist on type